generated_at = "2026-07-28T09:37:40Z"
generated_by = "kagami auto-discover --write-cache"
source_mtime_iso = "2026-06-20T02:37:15Z"
source_sha = "e5eda47"

[[scopes]]
discovered_via = "swift-package-ast"
language = "swift"
module_patterns = ["CoreKitTests"]
name = "CoreKitTests"
package_path = "/Users/jeoffrey/.shikki/workspaces/personal/packages/CoreKit"
source_paths = ["Tests/CoreKitTests/"]
test_command = ["swift", "test", "--filter", "CoreKitTests"]
test_file_patterns = []
test_target_name = "CoreKitTests"
type_patterns = []
